# app/domain/indicators/factory.py
from typing import Any, Dict, Type, List
import pandas as pd
from app.domain import *
from app.domain.operations.indicators.base_indicator import BaseIndicator
from app.domain.operations.indicators.sma_indicator import SmaIndicator
from app.domain.operations.indicators.ema_indicator import EmaIndicator
from app.domain.operations.indicators.rsi_indicator import RsiIndicator
from app.domain.operations.indicators.donchian_indicator import DonchianIndicator
from app.domain.operations.indicators.breakout_indicator import BreakoutIndicator
from app.domain.operations.indicators.macd_indicator import MACDIndicator
from app.domain.operations.indicators.tema_indicator import TemaIndicator
from app.domain.operations.indicators.wma_indicator import WmaIndicator
from app.domain.operations.indicators.vola_indicator import VolatilityIndicator
from app.domain.operations.indicators.atr_indicator import AtrIndicator
from app.domain.models.indicators.indicator_model import IndicatorModel
from app.domain.operations.indicators.bbands_indicator import BbandsIndicator
from app.domain.operations.indicators.roc_indicator import RocIndicator

from app.domain.domain_config import DOMAIN_CONFIG

class IndicatorFactory:  

    @staticmethod
    def create_indicator(strategy_type: IndicatorEnum) -> BaseIndicator:
        match strategy_type:
            case IndicatorEnum.SMA:
                return SmaIndicator()
            case IndicatorEnum.EMA:
                return EmaIndicator()
            case IndicatorEnum.WMA:
                return WmaIndicator()
            case IndicatorEnum.TEMA:
                return TemaIndicator()
            case IndicatorEnum.MACD:
                return MACDIndicator()
            case IndicatorEnum.RSI:
                return RsiIndicator()
            case IndicatorEnum.DONCHIAN:
                return DonchianIndicator()
            case IndicatorEnum.BREAKOUT:
                return BreakoutIndicator()
            case IndicatorEnum.VOLA:
                return VolatilityIndicator()
            case IndicatorEnum.ATR:
                return AtrIndicator()
            case IndicatorEnum.BBANDS:
                return BbandsIndicator()
            case IndicatorEnum.ROC:
                return RocIndicator()
            case _:
                raise ValueError(f"Unsupported strategy type: {strategy_type}")

    @staticmethod
    def extend_dataframe_with_indicators(
        df: pd.DataFrame,
        indicator_models: List[IndicatorModel]
    ) -> pd.DataFrame:
        initial_cols = set(df.columns)
        for indicator_model in indicator_models:
            if isinstance(indicator_model, IndicatorModel):
                indicator = IndicatorFactory.create_indicator(indicator_model.strategyType)
                df = indicator.create_features(df, indicator_model.params)
        new_cols = set(df.columns) - initial_cols
        if not new_cols:
            raise ValueError("No features were generated by the selected indicators. At least one feature is required.")
        return df
    
    @staticmethod
    def get_indicator_models_by_params(params: Dict[str, Any]) -> List[IndicatorModel]:
      
        result = []
        grouped = {}  
            
        for k, v in params.items():
            prefix = k.split('_')[0]
            if prefix in DOMAIN_CONFIG["INDICATOR_MAP"]:
                grouped.setdefault(prefix, {})[k] = v
                    
        for k in grouped.keys():
            enum = DOMAIN_CONFIG["INDICATOR_MAP"].get(k)
            param_dict = grouped.get(k, {})
            result.append(IndicatorModel(strategyType=enum, 
                                         params=json.dumps(param_dict),
                                         feature=DOMAIN_CONFIG["INDICATOR_FEATURES"][enum.name] if enum.name in DOMAIN_CONFIG["INDICATOR_FEATURES"] else ""))
            
        return result
    


